---
- hosts: "{{ ip }}"
  remote_user: root
  vars_files: vars/var.yml
  tasks:
    - name: Install client
      yum:
        name: ipa-client
        state: present

    - name: Set up FQDN
      hostname:
        name: "{{ host_name }}"

    - name: xxx
      shell: echo "10.10.118.235 ipa.xxx.com" >> /etc/hosts

    - name: Add ipa host
      ipa_host:
        name: "{{ host_name }}"
        ip_address: "{{ inventory_hostname }}"
        state: present
        ipa_host: ipa.xxx.com
        ipa_user: admin
        validate_certs: False
        ipa_pass: "{{ secret }}"
        random_password: True
        ipa_port: 443
      delegate_to: 127.0.0.1
      register: dic_content

    - name: Download ca
      get_url:
        url: https://xxx.ininin.com/ipa/config/ca.crt
        dest: /etc/ipa/ca.crt
        validate_certs: false


    - name: Set up ipa client
      shell: ipa-client-install --domain=xxx.com  --server=ipa.xxx.com --mkhomedir --unattended  --no-ntp -w  "{{ dic_content.host.randompassword }}" --ca-cert-file=/etc/ipa/ca.crt
      ignore_errors: True
